[project]
name = "opengl-jp"
version = "0.1.0"
description = ""
authors = [{ name = "Tatsuya Yatagawa", email = "tatsy.mail@gmail.com" }]
license = "CC-BY-SA-4.0"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11.0,<3.13.0"
dependencies = [
  "numpy>=2.2.4",
  "pyrr>=0.10.3",
  "glfw==2.5.0",
  "PyOpenGL==3.1.5",
  "pillow>=11.2.1",
  "open3d>=0.19.0",
]

[dependency-groups]
dev = ["mypy>=1.18.2", "ruff>=0.12.9"]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
length-sort = true
length-sort-straight = true

[tool.mypy]
python_version = "3.11"
follow_imports = "silent"
disallow_any_generics = true
strict_optional = true
check_untyped_defs = true
allow_redefinition = true
