source "https://rubygems.org"
gem "jekyll", "~> 4.0.0"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-feed"
  gem "jekyll-paginate"
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo"
  gem "tzinfo-data"
end

gem "wdm", :install_if => Gem.win_platform?
gem "rouge"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "webrick"
gem "i18n"


